#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void drive(int left, int right)
{
	motor[leftMotor] = left;
	motor[rightMotor] = right;
}

task main()
{
	drive(80, 30);
	delay(4020);
	drive(0, 0);
	drive(27, 83);
	delay(3810);
	drive(0, 0);

}
