#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void drive(int left, int right)
{
	motor[motorB] = left;
	motor[motorC] = right;
}

task main()
{
	drive(50,50);
	delay(1000);
	drive(70,0);
	delay(1000);
	drive(50,50);
	delay(1000);
	drive(70,0);
	delay(700);
	drive(50,50);
	delay(1000);
	drive(70,0);
	delay(1000);
	drive(50,50);
	delay(1000);

}
