#pragma config(Sensor, S3,     colorSensor,    sensorEV3_Color)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	// brown: 30
	// red: 48
	// green: 7
	while (true)
	{
		int colorIndex = getColorReflected(S3);
		// if green (reached end)
		if (colorIndex < 15)
		{
			motor[motorB] = 0;
			motor[motorC] = 0;
			displayBigTextLine(4, "green");
			delay(100);
		}
		// brown
		else if (colorIndex < 40)
		{
			motor[motorC] = 20;
			motor[motorB] = 0;
			displayBigTextLine(4, "brown");
		}
		// red
		else
		{
			motor[motorB] = 20;
			motor[motorC] = 0;
			displayBigTextLine(4, "red");
		}
	}

}
