#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	motor[leftMotor] = 80;
	motor[rightMotor] = 80;
	delay(4000);
	motor[leftMotor] = 0;
	motor[rightMotor] = 0;

}
