#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	motor[motorB] = 40;
	motor[motorC] = 40;
	delay(5300);
	motor[motorC] = 40;
	motor[motorB] = 0;
	delay(800);
	motor[motorB] = 40;
	motor[motorC] = 40;
	delay(1600);
	motor[motorB] = 80;
	motor[motorC] = 60;
	delay(9300);
	motor[motorC] = 60;
	motor[motorB] = 0;
	delay(610);
	motor[motorB] = 60;
	delay(4000);
	motor[motorC] = -60;
	delay(700);

}
